# Generated by Django 4.0.3 on 2022-03-03 23:04

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time_minutes', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(null=True, upload_to=recipes.models.recipe_image_file_path)),
                ('ingredients', models.ManyToManyField(blank=True, to='recipes.ingredient')),
                ('tags', models.ManyToManyField(blank=True, to='recipes.tag')),
            ],
        ),
    ]
